env: flex
runtime: nodejs
skip_files:
  - yarn\.lock
  - node_modules/
env_variables:
  API_VAR: 'ifQw00jC3LtQS4c4rfSbJOJFY7EmTvWP'
  API_HOST: 'marketcheck-test.apigee.net'
#handlers:
#- url: .*
#  script: index.js
#  secure: always
